services:

  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: shop-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - shop-pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shop-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - shop-pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres


# Kafka в режиме KRaft (без ZooKeeper)
  kafka:
    image: confluentinc/cp-kafka:latest  # или apache/kafka:3.7.0 и выше
    container_name: shop-kafka
    ports:
      - "9092:9092" # для подключения из приложения (с хоста)
      - "29092:29092"     # альтернативный порт
    environment:
    # --- KRaft: этот узел — и брокер, и контроллер ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller #Говорит Kafka, что этот узел будет одновременно хранить данные (broker)
      #и управлять метаданными кластера (controller), заменяя собой ZooKeeper.

      # --- Настройка контроллера (заменяет ZooKeeper) ---
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093 #Единственный голосующий узел — он сам. Список узлов-контроллеров. Для одного узла указываем его самого.
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk" # Фиксированный ID для кластера. Уникальный ID кластера. Можно сгенерировать любой, например, с помощью команды kafka-storage.sh random-uuid.

      # --- Настройка листенеров ---
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # --- Базовые настройки для одного узла ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"  # Топики будут создаваться автоматически при первой отправке сообщения, без необходимости ручного создания через конфигурацию

  # Опционально - Kafka UI для просмотра топиков
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: shop-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092


volumes:
  shop-pgdata:
  shop-pgadmin-data: