services:
  postgres:
    image: postgres:16
    container_name: online-shop-db
    restart: always
    environment:
      POSTGRES_DB: online_shop
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: