#APPLICATION
spring.application.name=online-shop
server.port=8081

#DATABASE
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=true
logging.level.org.hibernate.tool.hbm2ddl=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

# KAFKA - KRAFT
spring.kafka.bootstrap-servers=localhost:29092

!--- Producer ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

!--- Consumer ---
spring.kafka.consumer.group-id=shop-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.shop.event
spring.kafka.consumer.auto-offset-reset=earliest
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=WARN


# EMAIL CONFIGURATION
# Gmail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SHOP_EMAIL}
spring.mail.password=${SHOP_EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


shop.email.from=noreply@shop.com

